name: Task_Manager
description: "simple task manager"
publish_to: 'none'
version: 1.0.3

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_slidable: 
  intl:
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

flutter_icons:
 android: true
 ios: true
 image_path: "assets/icon/icon.png"